### POST request to create patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Cena with billing account",
  "email": "johncenabilling@gmail.com",
  "address": "Delhi",
  "dateOfBirth": "2000-01-15",
  "registeredDate": "2026-04-23"
}
