### POST request to create patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Tom",
  "email": "tom@gmail.com",
  "address": "London",
  "dateOfBirth": "1998-12-09",
  "registeredDate": "2026-03-10"
}
